# Combining DataFrames With Pandas - Lab

## Introduction

In this lab, you'll gain practice combining DataFrames through concatenation.  You'll also practice executing various types of joins to selectively combine the information stored in the tables!

## Objectives

In this lab you will:

- Use concatenation to combine DataFrames  
- Determine which type of join is preferred for two tables of data and a task  
- Use different types of joins to merge dataframes


## Concatenating DataFrames

Run the cell below to create some sample DataFrames for us to work with.

In [1]:
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])


df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'], 
                    'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8, 9, 10, 11])

Now that you have multiple DataFrames to work with, you can execute a concatenation to join them together.  

In the cell below, concatenate the 3 DataFrames together using the appropriate function.

In [3]:
combined_df = pd.concat([df1,df2,df3])
combined_df

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

**_EXPECTED OUTPUT:_**

<img src="images/er1.png">

## Setting join conditions with concatenation

You can also specify if the concatenation is an **_Outer Join_** or an **_Inner Join_**.  Next, you'll execute an inner join. Before you do, you need to create another table that contains some overlapping index values with a DataFrame that already exists. 

Run the cell below to create the new DataFrame.

In [5]:
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                    'D': ['D2', 'D3', 'D6', 'D7'],
                    'F': ['F2', 'F3', 'F6', 'F7']},
                    index=[2, 3, 6, 7])

Now, in the cell below, use the `pd.concat()` function to join DataFrames 1 and 4.  However, this time, specify that the `join` is `'inner'`, and `axis=1`.

In [8]:
df1_and_4 = pd.concat([df1,df4], join = 'inner', axis = 1)
df1_and_4

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

**_EXPECTED OUTPUT:_**

<img src='images/er2.png'>

You'll notice that in this case, the results contain only the rows with indexes that exist in both tables -- rows 2 and 3.  The resulting table contains the values for each column in both tables for the rows.  

Note that there are many, many ways that you can make full use of the `pd.concat()` function in pandas to join DataFrames together -- these are just a few of the most common examples pulled from the pandas documentation on the subject. For a full view of all the ways you can use `pd.concat()`, see the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/merging.html)!

## Load data
Now, it's time to move on to working with the Hearthstone cards database.  This database contains information on cards from the popular game, [Hearthstone](https://playhearthstone.com/en-us/)! For full information on the dataset, see the [Kaggle page](https://www.kaggle.com/jeradrose/hearthstone-cards) for this dataset. 

This database consists of the following tables:

* _cards_
* *dust_costs*
* _entourages_
* _mechanics_
* *play_requirements*

Many of rows in each table -- but not all -- correspond to the same cards. As such, each table contains a column called `card_id` which acts as a **_Primary Key_** for each table.  You'll make use of these keys to **_join_** the different tables together into a single DataFrame. You'll also experiment with different types of joins to help us decide exactly what information you wish to combine.  

Simply run the cell below to import the tables from the database as DataFrames.

In [17]:
cards_df = pd.read_csv('cards.csv')
dust_df = pd.read_csv('dust.csv')
entourages_df = pd.read_csv('entourages.csv')
mechanics_df = pd.read_csv('mechanics.csv')
play_requirements_df = pd.read_csv('play_requirements.csv')

Great.  Now, let's set the correct column, `card_id`, as the index column for each of these tables, and then display each to ensure that everything is as expected.  

For each of the DataFrames you created in the cell above, call the `.set_index()` method and pass in `card_id`.  Also set `inplace=True`.  Then, display the `.head()` of each respective DataFrame to ensure everything worked.  

**_NOTE:_** Since you are performing this operation in place, running any cell a second time will result in pandas throwing an error.  If you need to run something a second time, restart the kernel using the jupyter notebook menu at the top of the page.

In [15]:
cards_df.set_index(cards_df.card_id, inplace=True)
cards_df.head()

,card_id,player_class,type,name,set,text,cost,attack,health,rarity,collectible,flavor,race,how_to_earn,how_to_earn_golden,targeting_arrow_text,faction,durability
card_id,,,,,,,,,,,,,,,,,,
KARA_00_07,KARA_00_07,MAGE,SPELL,Astral Portal,KARA,Summon a random <b>Legendary</b> minion.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NEW1_008a,NEW1_008a,DRUID,SPELL,Ancient Teachings,EXPERT1,Draw a card.,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRM_010t2,BRM_010t2,DRUID,MINION,Druid of the Flame,BRM,NaN,3.0,2.0,5.0,COMMON,NaN,NaN,BEAST,NaN,NaN,NaN,NaN,NaN
AT_132,AT_132,NEUTRAL,MINION,Justicar Trueheart,TGT,<b>Battlecry:</b> Replace your starting Hero P...,6.0,6.0,3.0,LEGENDARY,1.0,It's like putting racing stripes and a giant s...,NaN,NaN,NaN,NaN,NaN,NaN
OG_141,OG_141,NEUTRAL,MINION,Faceless Behemoth,OG,NaN,10.0,10.0,10.0,COMMON,1.0,"Rejected names: Forty-Foot Faceless, Big ol' N...",NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
dust_df.set_index(dust_df.card_id, inplace=True)

In [20]:
entourages_df.set_index(entourages_df.card_id, inplace=True)

In [21]:
mechanics_df.set_index('card_id', inplace=True)

In [23]:
play_requirements_df.set_index('card_id', inplace=True)

## Executing Joins

Now that you have the tables loaded correctly, we're going to execute some joins. There are four different kinds of joins, which can best be visualized with Venn diagrams:

<img src='images/Image_198_joins.png'>

In these diagrams, each circle represents a DataFrame or SQL Table. The left table is the table you are working with, and the right table is the table you want to join to the table you are working with. You'll start by executing the most common type of join, an **_Inner Join_**.

In the cell below, join `cards_df` with `mechanics_df` using the built-in `.join()` method on the `cards_df` object. 

Pass in the following parameters:
* the table you want to join with, `mechanics_df`
* The `how` parameter set to the type of join you want, `'inner'`

In [27]:
cards_with_mechanics_df = cards_df.join(mechanics_df, how = 'inner')
cards_with_mechanics_df.head()

Empty DataFrame
Columns: [card_id, player_class, type, name, set, text, cost, attack, health, rarity, collectible, flavor, race, how_to_earn, how_to_earn_golden, targeting_arrow_text, faction, durability, mechanic]
Index: []

Examine the output from the cell above and compare it to the original output of both the `cards_df` and `mechanics_df` DataFrame heads you displayed earlier.  Notice how this now combines the columns from both?

**_Question_**

If you inspect the original `cards_df` DataFrame, you'll notice that it contains  2,819 records.  The result of our inner join, `cards_with_mechanics_df`, contains only 1079 rows.  Why?

Write your answer below this line:
________________________________________________________________________________
Inner joins only join together records that are present in both data tables. The 2 tables only had 1079 records in common.

## Other Types of Joins

By default, the `.join()` method performs a left join if no parameter is passed in for `how=`.  In the cell below, perform a **_Left Join_** of `cards_with_mechanics_df` and `play_requirements_df`, with `cards_with_mechanics_df` as the left table.  

Then, display `left_join_df` to inspect our results.

In [28]:
left_join_df = cards_with_mechanics_df.join(play_requirements_df)
left_join_df

Empty DataFrame
Columns: [card_id, player_class, type, name, set, text, cost, attack, health, rarity, collectible, flavor, race, how_to_earn, how_to_earn_golden, targeting_arrow_text, faction, durability, mechanic, play_requirement, value]
Index: []

[0 rows x 21 columns]

Note that the results of this sort of join are dependent upon the position of each table--if you were to make `cards_with_mechanics_df` the right table and `play_requirements_df` the left table and then perform a **_Right Join_**, our results would be the same. 

**_Question:_**

Describe what was included from each table in this join.

Write your answer below this line:
# Every record from cards_with_mechanics_df, as well as any records from play_requirements_df that have matching index values 
# with a record from the left table.  
________________________________________________________________________________

#### Outer Joins

In the cell below, perform an outer join between `cards_df` and `dust_df`. Since these tables contain columns with the same name, we'll need to specify a suffix for at least one of them, so that the column can be renamed to avoid a naming collision. 

During this join, set the `rsuffix` parameter to `_dust`

In [29]:
outer_join_df = cards_df.join(dust_df, how = 'outer', rsuffix = '_dust')
outer_join_df

,card_id,player_class,type,name,set,text,cost,attack,health,rarity,...,flavor,race,how_to_earn,how_to_earn_golden,targeting_arrow_text,faction,durability,card_id_dust,action,cost_dust
0,KARA_00_07,MAGE,SPELL,Astral Portal,KARA,Summon a random <b>Legendary</b> minion.,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NEW1_008a,DRUID,SPELL,Ancient Teachings,EXPERT1,Draw a card.,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BRM_010t2,DRUID,MINION,Druid of the Flame,BRM,NaN,3.0,2.0,5.0,COMMON,...,NaN,BEAST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AT_132,NEUTRAL,MINION,Justicar Trueheart,TGT,<b>Battlecry:</b> Replace your starting Hero P...,6.0,6.0,3.0,LEGENDARY,...,It's like putting racing stripes and a giant s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,OG_141,NEUTRAL,MINION,Faceless Behemoth,OG,NaN,10.0,10.0,10.0,COMMON,...,"Rejected names: Forty-Foot Faceless, Big ol' N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CRED_17,NEUTRAL,MINION,Rob Pardo,CREDITS,You can't start a game without this minion in ...,9.0,9.0,9.0,LEGENDARY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,OG_337e,NEUTRAL,ENCHANTMENT,Eve of Destruction,OG,Stats increased.,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,BRMA08_1H,NEUTRAL,HERO,General Drakkisath,BRM,NaN,NaN,NaN,50.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,GVG_011a,NEUTRAL,ENCHANTMENT,Shrink Ray,GVG,-2 Attack this turn.,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NAX8_02H_TB,NEUTRAL,HERO_POWER,Harvest,TB,<b>Hero Power</b>\nDraw a card. Gain a Mana Cr...,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,AT_131,NEUTRAL,MINION,Eydis Darkbane,TGT,Whenever <b>you</b> target this minion with a ...,3.0,3.0,4.0,LEGENDARY,...,"HATES being called ""the wonder twins"".",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,CS2_122e,NEUTRAL,ENCHANTMENT,Enhanced,CORE,Raid Leader is granting this minion +1 Attack.,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,LOEA05_02ha,NEUTRAL,HERO_POWER,Trogg Hate Minions!,LOE,<b>Passive Hero Power</b>\n Enemy minions cost...,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CS2_102_H1_AT_132,WARRIOR,HERO_POWER,Tank Up!,HERO_SKINS,<b>Hero Power</b>\nGain 4 Armor.,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,CFM_334e,NEUTRAL,ENCHANTMENT,Smuggling,GANGS,+2/+2 from Smuggler's Crate.,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,EX1_583,NEUTRAL,MINION,Priestess of Elune,EXPERT1,<b>Battlecry:</b> Restore 4 Health to your hero.,6.0,5.0,4.0,COMMON,...,"If she threatens to ""moon"" you, it's not what ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,TB_PickYourFate_11rand,NEUTRAL,SPELL,Dire Fate: Murlocs,TB,Turn each minion in play into a 1/1 Murloc.,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,LOE_007t,WARLOCK,SPELL,Cursed!,LOE,"While this is in your hand, take 2 damage at t...",2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,CFM_095,NEUTRAL,MINION,Weasel Tunneler,GANGS,<b>Deathrattle:</b> Shuffle this minion into y...,1.0,1.0,1.0,EPIC,...,He's the reason the First Bank of Gadgetzan ha...,BEAST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,BRM_018,PALADIN,MINION,Dragon Consort,BRM,<b>Battlecry:</b> The next Dragon you play cos...,5.0,5.0,5.0,RARE,...,Everybody wants someone to snuggle with. Even ...,DRAGON,"Unlocked in Blackrock Spire, in the Blackrock ...","Crafting unlocked in Blackrock Spire, in the B...",NaN,NaN,NaN,NaN,NaN,NaN
20,PRO_001a,NEUTRAL,SPELL,I Am Murloc,PROMO,"Summon three, four, or five 1/1 Murlocs.",4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,BRMA10_5H,NEUTRAL,MINION,Chromatic Drake,BRM,NaN,4.0,7.0,7.0,NaN,...,NaN,DRAGON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,BRMA11_1,NEUTRAL,HERO,Vaelastrasz the Corrupt,BRM,NaN,NaN,NaN,30.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,OG_027,SHAMAN,SPELL,Evolve,OG,Transform your minions into random minions tha...,1.0,NaN,NaN,RARE,...,"So you say you want an evolution. Well, you kn...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NAX1_01,NEUTRAL,HERO,Anub'Rekhan,NAXX,NaN,NaN,NaN,30.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,GVG_030,DRUID,MINION,Anodized Robo Cub,GVG,<b>Taunt</b>. <b>Choose One -</b>\n+1 Attack; ...,2.0,2.0,2.0,COMMON,...,It's adorable! AND OH MY GOODNESS WHY IS IT EA...,MECHANICAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,CFM_094,WARLOCK,SPELL,Felfire Potion,GANGS,Deal $5 damage to all characters.,6.0,NaN,NaN,RARE,...,Kazakus has a squad of imps bottling Felfire r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,DS1h_292_H1,HUNTER,HERO_POWER,Steady Shot,HERO_SKINS,<b>Hero Power</b>\nDeal $2 damage to the enemy...,2.0,NaN,NaN,FREE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,CS2_227,NEUTRAL,MINION,Venture Co. Mercenary,EXPERT1,Your minions cost (3) more.,5.0,7.0,6.0,COMMON,...,No Job is too big. No fee is too big.,NaN,NaN,NaN,NaN,HORDE,NaN,NaN,NaN,NaN
29,KAR_062,NEUTRAL,MINION,Netherspite Historian,KARA,"<b>Battlecry:</b> If you're holding a Dragon, ...",2.0,1.0,3.0,COMMON,...,She can tell you all about the history of peop...,NaN,"Unlocked in the Spire, in One Night in Karazhan.","Crafting unlocked in the Spire, in One Night i...",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
OG_338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_338,DISENCHANT_NORMAL,400.0
OG_338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_338,DISENCHANT_GOLDEN,1600.0
OG_339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_339,CRAFTING_NORMAL,100.0
OG_339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_339,CRAFTING_GOLDEN,800.0
OG_339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_339,DISENCHANT_NORMAL,20.0
OG_339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_339,DISENCHANT_GOLDEN,100.0
OG_340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_340,CRAFTING_NORMAL,1600.0
OG_340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_340,CRAFTING_GOLDEN,3200.0
OG_340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_340,DISENCHANT_NORMAL,400.0
OG_340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OG_340,DISENCHANT_GOLDEN,1600.0
TB_OG_027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TB_OG_027,CRAFTING_NORMAL,100.0
TB_OG_027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TB_OG_027,CRAFTING_GOLDEN,800.0
TB_OG_027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TB_OG_027,DISENCHANT_NORMAL,20.0
TB_OG_027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TB_OG_027,DISENCHANT_GOLDEN,100.0
skele21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skele21,CRAFTING_NORMAL,40.0
skele21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skele21,CRAFTING_GOLDEN,400.0
skele21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skele21,DISENCHANT_NORMAL,5.0
skele21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skele21,DISENCHANT_GOLDEN,50.0
tt_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_004,CRAFTING_NORMAL,40.0
tt_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_004,CRAFTING_GOLDEN,400.0
tt_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_004,DISENCHANT_NORMAL,5.0
tt_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_004,DISENCHANT_GOLDEN,50.0
tt_010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_010,CRAFTING_NORMAL,400.0
tt_010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_010,CRAFTING_GOLDEN,1600.0
tt_010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_010,DISENCHANT_NORMAL,100.0
tt_010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_010,DISENCHANT_GOLDEN,400.0
tt_010a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_010a,CRAFTING_NORMAL,400.0
tt_010a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_010a,CRAFTING_GOLDEN,1600.0
tt_010a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_010a,DISENCHANT_NORMAL,100.0
tt_010a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt_010a,DISENCHANT_GOLDEN,400.0

Inspect the output above.  Note that the naming collision has been avoided by renaming the `cost` column from the right table to `cost_dust`.  

## Summary

In this lab, you learned how to:

* Concatenate multiple DataFrames together into a single DataFrame
* Understand and execute the various types of joins (inner, outer, left, and right joins)